default: cpsc2150 cpsc2150 cpsc2150 cpsc2150 cpsc2150
	javac cpsc2150/MyVector/ArrayVector.java cpsc2150/MyVector/DoubleVectorApp.java cpsc2150/MyVector/IVector.java cpsc2150/MyVector/ListVector.java cpsc2150/MyVector/AbsVector.java

run: cpsc2150 cpsc2150 cpsc2150 cpsc2150 cpsc2150
	java cpsc2150.MyVector.DoubleVectorApp

clean:
	rm -f cpsc2150/MyVector/*.class